name: CMS CI

on:
  pull_request:
    branches:
      - "*"
  push:
      branches:
        - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Go 1.24.1
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
        id: go

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Test
        run: make test